### ISSUE TITLE
Unit test job broken by #73

### ISSUE THREAD

**Issue by russellb** [instructlab/sdg#147]
After merging #73 

```
$ tox -e unit

================================================================================================== ERRORS ==================================================================================================
_________________________________________________________________________________ ERROR collecting tests/test_llmblock.py __________________________________________________________________________________
tests/test_llmblock.py:9: in <module>
    from src.instructlab.sdg.llmblock import LLMBlock
src/instructlab/sdg/__init__.py:29: in <module>
    from .importblock import ImportBlock
src/instructlab/sdg/importblock.py:6: in <module>
    from . import pipeline
src/instructlab/sdg/pipeline.py:102: in <module>
    "ImportBlock": importblock.ImportBlock,
E   AttributeError: partially initialized module 'src.instructlab.sdg.importblock' has no attribute 'ImportBlock' (most likely due to a circular import)
========================================================================================= short test summary info ==========================================================================================
ERROR tests/test_llmblock.py - AttributeError: partially initialized module 'src.instructlab.sdg.importblock' has no attribute 'ImportBlock' (most likely due to a circular import)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================================= 1 error in 1.72s =============================================================================================
unit: exit 2 (2.22 seconds) /Users/rbryant/src/instructlab/sdg> .tox/unit/bin/python -m pytest tests pid=11850
  unit: FAIL code 2 (4.04=setup[1.82]+cmd[2.22] seconds)
  evaluation failed :( (4.32 seconds)
```
