### PR TITLE
Revert "Export more public APIs in top-level package"

### LINKED ISSUE #147: Unit test job broken by #73
After merging #73 

```
$ tox -e unit

================================================================================================== ERRORS ==================================================================================================
_________________________________________________________________________________ ERROR collecting tests/test_llmblock.py __________________________________________________________________________________
tests/test_llmblock.py:9: in <module>
    from src.instructlab.sdg.llmblock import LLMBlock
src/instructlab/sdg/__init__.py:29: in <module>
    from .importblock import ImportBlock
src/instructlab/sdg/importblock.py:6: in <module>
    from . import pipeline
src/instructlab/sdg/pipeline.py:102: in <module>
    "ImportBlock": importblock.ImportBlock,
E   AttributeError: partially initialized module 'src.instructlab.sdg.importblock' has no attribute 'ImportBlock' (most likely due to a circular import)
========================================================================================= short test summary info ==========================================================================================
ERROR tests/test_llmblock.py - AttributeError: partially initialized module 'src.instructlab.sdg.importblock' has no attribute 'ImportBlock' (most likely due to a circular import)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================================= 1 error in 1.72s =============================================================================================
unit: exit 2 (2.22 seconds) /Users/rbryant/src/instructlab/sdg> .tox/unit/bin/python -m pytest tests pid=11850
  unit: FAIL code 2 (4.04=setup[1.82]+cmd[2.22] seconds)
  evaluation failed :( (4.32 seconds)
```

### PR DESCRIPTION
**Pull request by russellb**
This reverts commit 40b45ad8196087fda02887a9257769d285c7302a.

Closes #147

Signed-off-by: Russell Bryant <rbryant@redhat.com>

### CODE REVIEW

**Comment by russellb** [comment]
This obviously isn't the ideal change, but I wanted to stage it here in case we decide this should go in to fix the unit test job

**Comment by russellb** [comment]
should close this once #153 merges
